@startuml
'https://plantuml.com/class-diagram


class User {
    - String firstName
    - String lastName
    - int sex
    - char[] login
    - char[] password
    - ArrayList<Card> cardArrayList
}

class Card {
    - long numberCard
    - int cardEndDataMonth
    - int cardEndDataYear
    - int CVC2
}

class Phone {
}

class System {
}
@enduml